var PngIcons = {
    logo: "/images/Logo.png",
    hero: "/images/hero.png",
    mission: "/images/mission.png",
    missionimg: "/images/missionimg.png",
    update1: "/images/update1.png",
    update2: "/images/update2.png",
    update3: "/images/update3.png",
    footerlogo: "/images/footerlogo.png",
    about: "/images/aboutbg.png",
    h1: "/images/abouth1.png",
    f1: "/images/f1.png",
    f2: "/images/f2.png",
    f3: "/images/f3.png",
    f4: "/images/f4.png",
    c1: "/images/C1.png",
    c2: "/images/C2.png",
    c3: "/images/C3.png",
    c4: "/images/C4.png",
    c5: "/images/C5.png",
    c6: "/images/C6.png",
    c7: "/images/C7.png",
    c8: "/images/C8.png",
    c9: "/images/C9.png",
    c10: "/images/C10.png",
    c11: "/images/C11.png",
    image1: "/images/image1.png",
    image2: "/images/image2.png",


}
export default PngIcons;