import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import { FaHandHoldingHeart } from "react-icons/fa";

import Footer from "@/component/Footer";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar */}
        <div className="fixed top-0 z-40 w-full">
          <Navbar />
        </div>

        {/* Main content area */}
        <main className="flex-1 relative pt-[4.5rem]">
          {children}
        </main>

        {/* Sticky button after 100vh */}

        <div className="fixed flex felx-column items-center bottom-4 right-9 z-50 w-full sm:w-auto">
          <Link href="/donate">
            <button className="bg-black w-[170px] py-3 text-white rounded-lg flex items-center justify-center space-x-2 hover:bg-white hover:text-black transition duration-300">
              <span className="pe-2">Donate Now</span>
              <FaHandHoldingHeart size={24} />
            </button>
          </Link>
        </div>

        {/* Footer */}
        <Footer />
      </body>
    </html>
  );
}
